### ISSUE TITLE
Has anyone actually managed to make this work with images loaded from a collection?

### ISSUE THREAD

**Issue by Achtel** [timbrandin/meteor-slick#2]
I'm struggling to initialise slick properly as the onRendered .slick call doesn't work with Meteor's asynchronous loading of subscriptions...

So `<template name="image">
  <div id="carousel">
    <div id="demo-box"><img src="../../img/brush.jpg" /></div>
    <div id="demo-box"><img src="../../img/drill.jpg" /></div>
    <div id="demo-box"><img src="../../img/hammer.jpg" /></div>
    <div id="demo-box"><img src="../../img/shovel.jpg" /></div>
    <div id="demo-box"><img src="../../img/spanner.jpg" /></div>
    <div id="demo-box"><img src="../../img/tape.jpg" /></div>
  </div>
</template>`

works fine but `<template name="image">
  {{#if Template.subscriptionsReady}}
    {{slickInit}}
    <div id="carousel">
      {{#each images}}
        <div id="demo-box"><img src="{{url}}" /></div>
      {{/each}}
    </div>  
  {{else}}
    <div>Loading...</div>
  {{/if}}
</template>`

doesn't... It just shows all images at once. I believe that's because they only get loaded _after_ the onRendered call has completed.

Has anyone managed to make this work?

**Comment by timbrandin** [comment]
Yeah, I usually initialize Slick from a template per item, and make sure to reset the whole batch. Or you could do something smart and add/remove items. But the simplest method is just to reset and reconstruct. I'm looking forward to new methods that are as good but with better reactive methods behind them, rather than the correct afterwards approach.

**Comment by Achtel** [comment]
Amazing, that totally works. Thanks for the hint. I've been trying to get this to work for a hours. Much appreciated.

**Comment by Achtel** [comment]
Too happy too soon? While it's working now the console gets flooded with 

```
Exception from Tracker afterFlush function:
debug.js:41 TypeError: Cannot read property 'add' of null
    at Slick.initADA (slick.js:2590)
    at Slick.init (slick.js:1215)
    at new Slick (slick.js:177)
    at $.fn.slick (slick.js:2662)
    at null.<anonymous> (image.js:36)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:457)
    at fireCallbacks (template.js:112)
    at null.<anonymous> (template.js:205)
    at view.js:107
```

every time I initialise slick on the imageItem template. Do you have the same issues, if so how do you handle this? It's not stopping the carousel from working, but it's a little untidy...

**Comment by timbrandin** [comment]
Have a look at this, it might lead you to a solution:
https://github.com/kenwheeler/slick/issues/542#issuecomment-160096706

**Comment by Achtel** [comment]
```
Template.imageItem.onRendered( () => {
  slick_slider();
});

function slick_slider() {
  var wrapper = $('#carousel');
  if ($(".slick-initialized").length == 0) {
    wrapper.slick({
      infinite: false,
      dots: true,
      slidesToShow: 3,
      slidesToScroll: 3,
      arrows: true
    });
  }
}

```

Works. Thanks for the hint.

**Comment by timbrandin** [comment]
Cool, glad it helped!

**Comment by timbrandin** [comment]
Here's a better solution, just unslick before you slick. ;)

```
Template.imageItem.onRendered( () => {
  slick_slider();
});

function slick_slider() {
  var $wrapper = $('#carousel');
  $wrapper.slick("unslick");
  $wrapper.slick({
    infinite: false,
    dots: true,
    slidesToShow: 3,
    slidesToScroll: 3,
    arrows: true
  });
}
```
